### ISSUE TITLE
Subdir support

### ISSUE THREAD

**Issue by uli-heller** [arnaudsm/raito#9] opened 2022-01-08 09:51 UTC
I forked raito and added subdir support to it (among others). Now I realized that there is a TODO list at the end of the README.md and "subdir support" shows up there.

Are you interested in a pull request?

Currently, my fork is probably way to fat but I'd factor out the subdir support in case you're interested.

Here, there are some examples of some nested subdirs to illustrate my understanding of the feature:

[issues.zip](https://github.com/arnaudsm/raito/files/7832985/issues.zip)
[subfolder-01.zip](https://github.com/arnaudsm/raito/files/7832988/subfolder-01.zip)

**Comment by arnaudsm** [comment] 2022-01-15 23:41
I'm sorry but `subdir support` was already implemented, but not documented. That's why it was checked in the todolist..
However there's great additions in your fork, thank you for your work!

Which new features would you like to merge ? I'd love to do a PR

**Comment by uli-heller** [comment] 2022-01-16 16:13
Hey Arnaud,

I've setup an instance of my fork of RAITO containing subfolders with relative links. I'm going to add these subfolders to a pull request. I guess these subfolders do work on my fork but not on the original raito.

See <https://uli-heller.github.io/raito/index.html#/subfolder-01/README.md> for the subfolders.

Are you going to support these kind of subfolders?

Thx, Uli

**Comment by arnaudsm** [comment] 2022-01-17 05:43
Subfolders with relative links already work in the original raito. Sorry for the misunderstanding, I just added documentation about it.
I also made an working example for you : https://github.com/arnaudsm/raito/tree/subdir-example

Is there any other feature you'd like to merge ?

**Comment by uli-heller** [comment] 2022-01-17 06:08
![subfolder-01-README md | Raito - Google Chrome_001](https://user-images.githubusercontent.com/1677414/149716404-e7fac666-53d6-4f10-a85a-5b4619558eae.png)

... this is how it looks for me. Clicking on the link gives me this:

![| Raito - Google Chrome_007](https://user-images.githubusercontent.com/1677414/149716497-77632d32-b5f4-44fb-9d40-50fa43be6c05.png)

Does not look OK to me!

**Comment by arnaudsm** [comment] 2022-01-23 06:11
This is not a bug, all markdown links should be relative (no starting /), and root directories should end with /.
Here's a [working example](https://github.com/arnaudsm/raito/tree/absolute-link-example) 

Since this was unclear, I'm adding more clarifications in the documentation.

**Closed as completed by arnaudsm** 2022-01-23 06:11 UTC
Labels: enhancement

**Comment by uli-heller** [comment] 2022-01-23 17:01
Ok, so you cannot use relative links within subfolders. I think this is quite bit unfortunate. But that's my personal opinion. Thx for taking the time looking at this.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

Am 23. Januar 2022 07:12:05 MEZ schrieb Arnaud de Saint Meloir ***@***.***>:

**Comment by arnaudsm** [comment] 2022-01-23 21:19
Sorry for the typo, I meant relative. Take a look at the example I made for you, it works perfectly!

**Comment by uli-heller** [comment] 2022-01-24 10:20
Your example uses relative paths but treats them as absolute paths, doesn't it?
See https://stackoverflow.com/questions/24028561/relative-path-in-html for some details
